apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-pvc
  namespace: rag-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: pv-llm-models
  resources:
    requests:
      storage: 20Gi
