apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-models-pvc
  namespace: rag-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: pv-hf-models
  resources:
    requests:
      storage: 10Gi
