apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdfs-pvc
  namespace: rag-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: pv-pdfs
  resources:
    requests:
      storage: 5Gi
