apiVersion: v1
kind: Service
metadata:
  name: rag-platform
  namespace: rag-platform
spec:
  selector:
    app: rag-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort